languageCode: en-us
title: Atmanaut
theme: chakra
# googleAnalytics: UA-123-45
params:
  author: Kerry Snyder
  description: "सच्चिदानन्द"
  summaryLength: 50
  preserveTaxonomyNames: true
permalinks:
  posts: /:year/:month/:title
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
