languageCode: en-us
title: Atmanaut
theme: chakra
params:
  author: "Kerry Snyder"
  description: "सच्चिदानन्द"
  summaryLength: 50
  preserveTaxonomyNames: true
  algolia:
    vars: ["title", "date", "summary", "permalink", "title_lead", "subtitle", "title_main"]
    params: ["tags", "categories"]
permalinks:
  posts: /:year/:month/:title
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
outputs:
  home: ["HTML", "RSS", "Algolia"]
outputFormats:
  Algolia:
    basename: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
algolia:
    index: atmanaut
    appID: 8ACVSKKUVV
    key: aa5b45b2a7ebf3d4133dee13429dccba
# googleAnalytics: UA-123-45
