---
languageCode: en-us
title: Atmanaut
baseUrl: https://atmanaut.me
module:
  imports:
  - path: github.com/krry/chakra-hugo-theme
author:
  name: Kerry Snyder
params:
  description: A place for explorers of the spirit we share, being knowing enjoying
  tagline: सच्चिदानन्द
  tagsLimit: 27
  summaryLength: 50
  preserveTaxonomyNames: true
  googleFontsURL: "https://fonts.googleapis.com/css2?family=Inconsolata:wght@300;500;700&family=MuseoModerno:wght@300;500;700&family=Quicksand:wght@300;500;700&display=swap"
  colors:
    base: "#280664"
    purp: "#5d17d9"
    blue: "#1695c5"
outputs:
  home:
  - html
  - json
  - rss
taxonomies:
  author: authors
  tag: tags
  category: categories
permalinks:
  posts: "/:year/:month/:title"
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
metaDataFormat: yaml
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
