languageCode = "en-us"
title = "Atmanaut"
theme = "chakra"
copyleft = "All lefts reversed."
# googleAnalytics = "UA-123-45"
[params]
  author = "krry a.k.a atmanaut"
  description = "a live atlas of atman"
