languageCode: en-us
title: Atmanaut
theme: chakra
author:
  name: "Kerry Snyder"
params:
  description: "A place for explorers of the spirit we share, being knowing enjoying"
  tagline: "सच्चिदानन्द"
  tagsLimit: 27
  summaryLength: 50
  preserveTaxonomyNames: true
  googleFontsURL: "https://fonts.googleapis.com/css?family=Lato:i:100,400,700|Aleo:100,400|Righteous|Inconsolata&amp;display=swap"
  colors:
    base: "#280664"
    purp: "#5d17d9"
    blue: "#1695c5"
taxonomies:
  author: "authors"
  tag: "tags"
  category: "categories"
permalinks:
  posts: /:year/:month/:title
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
metaDataFormat: yaml
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
googleAnalytics: UA-170088360-1
