languageCode: en-us
title: Atmanaut
theme: chakra
params:
  author: "Kerry Snyder"
  description: "सच्चिदानन्द"
  summaryLength: 50
  preserveTaxonomyNames: true
  colors:
    base: "#280664"
    purp: "#5d17d9"
    blue: "#1695c5"
taxonomies:
  author: "authors"
  tag: "tags"
  category: "categories"
permalinks:
  posts: /:year/:month/:title
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
