[build]
publish = "public"
command = "hugo --gc --minify -c ./content/posts"

[context.production.environment]
HUGO_VERSION = "0.82.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo -c ./content/posts"

[context.split1.environment]
HUGO_VERSION = "0.82.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL -c ./content/posts"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL -c ./content/posts"

[context.branch-deploy.environment]
HUGO_VERSION = "0.82.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
