---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: All
  create: all
  match: "**/*"
- type: directory
  path: content/tags
  label: Tags
  create: all
  match: "**/*"
  templates:
  - tag
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month/:filename:"
build:
  preview_command: cd themes/chakra && npm install postcss-cli -g  && ls -al && npm
    install && cd ../.. && hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
